### ISSUE TITLE
List Index out of Range on First Movie.

### ISSUE THREAD

**Issue by Adam-North** [Mike7154/plex_family_management#11]
Error when trying to run the script for the first time. It fails on the first movie.

there are 2030 Unlabeled moves that I will search for common sense media ages
saving movie data
*batteries not included
searching *batteries not included in common sense media
https://www.commonsensemedia.org/movie-reviews/batteries-not-included

Traceback (most recent call last):
  File "/home/anorth/plex_family_management/update_library.py", line 101, in <module>
    m_dict = csmedia.CSM_get(movie, m_dict, movies, library_type, csm_URLs, update_age_factor, library_types, parents_review)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anorth/plex_family_management/csmedia.py", line 201, in CSM_get
    movie_dict = scrape_CSM_page(movie_dict, page, parents_review)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anorth/plex_family_management/csmedia.py", line 93, in scrape_CSM_page
    to_know = cl_search_txt(soup, "div[class^=review-view-parents-need-know]")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anorth/plex_family_management/csmedia.py", line 13, in cl_search_txt
    return container[index].text
           ~~~~~~~~~^^^^^^^
IndexError: list index out of range

**Comment by Adam-North** [comment]
I was able to get your development branch working on Ubuntu after upgrading the openai api. But is there an easy way to disable the ChatGPT calls? I do not want summaries just age labels.
