### ISSUE TITLE
Some issues.

### ISSUE THREAD

**Issue by lailoken** [Mike7154/plex_family_management#12]
Firstly when trying the installation instructions I get:

```
~/plex/plex_family_management$ py -m pip install -r requirements.txt
usage: py [-x] [-l] [-c PRE_CMD] [-C POST_CMD] [-V] [-h] [expression]
py: error: unrecognized arguments: -m install -r requirements.txt
```

Even the following did not work:
```
~/plex/plex_family_management$ python3 -m pip install -r requirements.txt
error: externally-managed-environment
```
... more error text

I eventually got it to work via many many edits, not sure what I did as I'm not an expert in python/py/pip/etc.

Then when finally running it, it failed on the first search:
```
~/plex/plex_family_management$ python3 update_library.py
<PlexServer:https://10-0-0-10.04>
Child1
1 Shanghai Noon
searching 1 Shanghai Noon in common sense media
1 Shanghai Noon search had no verified results, trying a shorter search
1 Shang
1 Shanghai Noon search had no verified results, trying a shorter search
1 Shang
1 Shanghai Noon Search only showed 1 unverified result. I'm going to use that
1 Shanghai Noon was pulled in but the match could not be verified
Traceback (most recent call last):
  File "/home/admin/plex/plex_family_management/update_library.py", line 68, in <module>
    m_dict = csmedia.CSM_get(movie, m_dict, movies, library_type, csm_URLs, update_age_factor, library_types, parents_review)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/plex/plex_family_management/csmedia.py", line 201, in CSM_get
    movie_dict = scrape_CSM_page(movie_dict, page, parents_review)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/plex/plex_family_management/csmedia.py", line 93, in scrape_CSM_page
    to_know = cl_search_txt(soup, "div[class^=review-view-parents-need-know]")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/plex/plex_family_management/csmedia.py", line 13, in cl_search_txt
    return container[index].text
           ~~~~~~~~~^^^^^^^
IndexError: list index out of range
```

**Comment by Adam-North** [comment]
unfortunately I fear the project has gone stale.
